[package]
name = "autorun-env"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
libloading = { workspace = true }

autorun-types = { path = "../autorun-types" }
autorun-lua = { path = "../autorun-lua" }
