[package]
name = "autorun-core"
version = "0.1.0"
edition = "2024"

[dependencies]
nestify = "0.3.3"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.5"
cap-std = "3.4.4"
anyhow = { workspace = true }
