[package]
name = "autorun"
version = "0.1.0"
edition = "2021"

[dependencies]
# For the gui itself
eframe = { version = "0.19.0" }

# To redirect stdout to the terminal
shh = "1.0.1"

# For robust error handling
thiserror = "1.0.32"

# Need this to get system info and find the Garry's Mod process.
sysinfo = "0.25.3"

# Getting dll exports
libloading = "0.7.3"

# Self explanatory
detour = { git = "https://github.com/lostinspiration/detour-rs.git", default-features = false }

# Getting the Garry's Mod program.
steamlocate = "1.0.2"

[target.'cfg(windows)'.dependencies]
injector = { path = "../injector" }