[package]
name = "autorun-steam"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(windows)'.dependencies]
dll-syringe = "0.17.0"
winreg = "0.55.0"
