[package]
name = "autorun-lua"
description = "A minimal, user friendly and dynamically loaded LuaJIT bindings. A minimal alternative to mlua."
version = "0.1.0"
edition.workspace = true
authors.workspace = true

[dependencies]
libloading = { workspace = true }
