[package]
name = "autorun-fs"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
cap-std = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = ["Win32_Storage", "Win32_Storage_FileSystem"] }
